#define SPECIES_SHADEKIN_YW			"GeneShadekin"
#define SPECIES_GREY_YW				"Grey"
#define SPECIES_KIGYAR_YW	"Kig-Yar"
#define SPECIES_SANGHEILI_YW		"Sangueili"
#define SPECIES_TVAOAN_KIGYAR_YW	"Tvaoan Kig-Yar"
#define SPECIES_UNGGOY_YW			"Unggoy"
